---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.v1
  resources:
  - namespace
  verbs:
  - update
  - watch
- apiGroups:
  - labels.dvir.io
  resources:
  - customlabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - labels.dvir.io
  resources:
  - customlabels/finalizers
  verbs:
  - update
- apiGroups:
  - labels.dvir.io
  resources:
  - customlabels/status
  verbs:
  - get
  - patch
  - update
