name: pre-merge
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  build-and-unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Go Vet
        run: go vet ./...
      - name: Go Lint
        run:
          -go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2
          -golangci-lint run
      - name: Unit-test
        run: make test